import { buildMetadata } from "@/lib/metadata";
import { JsonLd } from "@/components/schema/JsonLd";
import { buildBreadcrumbSchema } from "@/lib/schema";
import { Breadcrumb } from "@/components/layout/Breadcrumb";
import { FinalCTA } from "@/components/sections/FinalCTA";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { SITE_URL } from "@/lib/utils";
import { BarChart2, Target, PieChart, TrendingUp, Zap, Brain, Shield, Smartphone, ArrowRight } from "lucide-react";

export const metadata = buildMetadata({
  title: "Marginfy Software | Profitability Intelligence Platform",
  description:
    "Marginfy Software — profitability intelligence platform with margin diagnostics, pricing optimisation, customer profitability and AI-generated insights. Your CFO in your pocket.",
  path: "/software",
});

const features = [
  {
    icon: BarChart2,
    title: "Product Profitability Analysis",
    desc: "See profitability by SKU, product line or service — including true cost allocation, not just revenue minus direct cost.",
  },
  {
    icon: Target,
    title: "Customer Profitability Scoring",
    desc: "Understand which customers are most profitable and which are costing you money when fully loaded costs are applied.",
  },
  {
    icon: PieChart,
    title: "Margin Diagnostics",
    desc: "Identify where margins are eroding — by product, period, channel or cost category — with drill-down capability.",
  },
  {
    icon: TrendingUp,
    title: "Pricing Optimisation",
    desc: "Scenario-test pricing changes and see the projected P&L impact before making changes.",
  },
  {
    icon: Zap,
    title: "Scenario Modelling",
    desc: "Model multiple business scenarios — volume shifts, cost changes, pricing moves — and see the full financial impact.",
  },
  {
    icon: Brain,
    title: "AI-Generated Insights",
    desc: "Receive contextual, plain-language insights generated by AI — surfacing anomalies, opportunities and risks automatically.",
  },
  {
    icon: Shield,
    title: "Forecasting",
    desc: "Rolling forward forecasts powered by your actual performance data, updated automatically as results come in.",
  },
  {
    icon: Smartphone,
    title: "Dashboard Reporting",
    desc: "Executive-level dashboards designed for decision-makers, not accountants. Mobile-ready for access anywhere.",
  },
];

export default function SoftwarePage() {
  return (
    <>
      <JsonLd schema={buildBreadcrumbSchema([
        { name: "Home", url: SITE_URL },
        { name: "Software", url: `${SITE_URL}/software` },
      ])} />

      <section className="bg-hero pt-32 pb-20">
        <div className="container">
          <div className="mb-6"><Breadcrumb items={[{ label: "Software" }]} /></div>
          <div className="max-w-3xl">
            <div className="inline-block text-sm font-semibold text-brand-green-400 bg-white/10 border border-white/20 px-3 py-1 rounded-full mb-6">
              Marginfy Software — Coming Soon
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold text-white mb-6 leading-tight">
              Your CFO{" "}
              <span className="text-brand-green-400">In Your Pocket</span>
            </h1>
            <p className="text-xl text-white/80 mb-4 leading-relaxed">
              Marginfy Software is a profitability intelligence platform for founder-led
              businesses. Real-time margin visibility, pricing insights and AI-generated
              recommendations — without needing a finance team.
            </p>
            <p className="text-white/60 mb-8">
              Currently in development. Register your interest below to be notified at launch.
            </p>
            <div className="flex flex-wrap gap-3">
              <Button variant="cta" size="lg" asChild>
                <Link href="/book-a-call">Register Interest <ArrowRight className="w-4 h-4" /></Link>
              </Button>
              <Button variant="hero" size="lg" asChild>
                <Link href="/book-a-call">Request Early Access</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      <section className="section-padding bg-white">
        <div className="container">
          <div className="max-w-3xl mx-auto text-center mb-12">
            <h2 className="text-3xl font-bold text-brand-navy mb-4">Platform Capabilities</h2>
            <p className="text-slate-600">
              Marginfy Software combines the analytical power of a finance team with the
              accessibility of modern SaaS — purpose-built for growing businesses.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {features.map((f) => (
              <div key={f.title} className="p-5 rounded-xl border border-slate-200 hover:border-brand-blue-200 hover:shadow-md transition-all bg-white">
                <f.icon className="w-6 h-6 text-brand-blue-600 mb-3" />
                <h3 className="font-semibold text-brand-navy mb-2 text-sm">{f.title}</h3>
                <p className="text-xs text-slate-600 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-padding bg-section-alt">
        <div className="container max-w-2xl text-center">
          <h2 className="text-3xl font-bold text-brand-navy mb-4">Register Your Interest</h2>
          <p className="text-slate-600 mb-8">
            Marginfy Software is in active development. Register your interest and
            we&apos;ll notify you when early access is available.
          </p>
          <Button variant="cta" size="xl" asChild>
            <Link href="/book-a-call">
              Get Early Access
              <ArrowRight className="w-4 h-4" />
            </Link>
          </Button>
        </div>
      </section>

      <FinalCTA />
    </>
  );
}
